M48
; DRILL file {KiCad (6.0.9-0)} date 2023 February 07, Tuesday 08:35:17
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-07T08:35:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X66.04Y-103.5
X66.04Y-150.5
X86.36Y-110.4
X86.36Y-143.6
T2
X63.5Y-40.35
X63.5Y-162.85
X88.9Y-40.35
X88.9Y-162.85
T0
M30
